pipelines:
  default:
    - step:
        script:
         - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
         - docker build -t udaysh/php7:$BITBUCKET_COMMIT .
         - docker push udaysh/php7:$BITBUCKET_COMMIT
options:
    docker: true