pipelines:
  tags:
    production-*:
    - parallel:
      - step:
          name: Install composer packages
          image: php:7.2
          services:
          - docker
          caches:
            - docker
            - composer
          script:
            - apt-get update && apt-get install -y unzip
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - cd symfony
            - APP_ENV=prod composer install --no-scripts --no-dev --no-suggest --optimize-autoloader
          artifacts:
            - symfony/vendor/**
      - step:
          name: Compile app assets
          image: node:10
          services:
            - docker
          caches:
            - docker
            - node
          script:
            - cd symfony
            - yarn && yarn build
          artifacts:
            - symfony/public/build/**
    - step:
        name: Build & upload final image
        image: atlassian/pipelines-awscli
        deployment: production
        services:
          - docker
        caches:
          - docker
        script:
          - export BUILD_ID=production_$BITBUCKET_BUILD_NUMBER
          - $(aws ecr get-login --no-include-email --region eu-west-1);
          - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          - docker build -t udaysh/php_v7.2_sf4:$BITBUCKET_COMMIT .
          - docker push udaysh/php_v7.2_sf4:$BITBUCKET_COMMIT
